name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3 python3-pip

      - name: Configure CMake
        run: cmake -S host_tests -B host_tests/build

      - name: Build
        run: cmake --build host_tests/build

      - name: Run tests
        run: ctest --test-dir host_tests/build --output-on-failure
