name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake python3 python3-pip
      - name: Run host unit tests (CMake)
        working-directory: host_tests
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
          ctest --output-on-failure
